"""empty message

Revision ID: 43dc978febba
Revises: 69344c4d7c36
Create Date: 2024-09-19 21:25:07.480547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dc978febba'
down_revision = '69344c4d7c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image')),
    sa.UniqueConstraint('imgname', name=op.f('uq_image_imgname'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
