"""empty message

Revision ID: a4b44aa51006
Revises: 390b800a9684
Create Date: 2024-09-21 14:52:11.939678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b44aa51006'
down_revision = '390b800a9684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('uq_image_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_image_name'), ['name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_image_name'), type_='unique')
        batch_op.create_unique_constraint('uq_image_name', ['name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
